# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    name: Auto-Documentation
    runs-on: ubuntu-latest
    
    steps:  # steps for the auto-documentation

      - uses: actions/checkout@master   # checks out repo so workflow can access it ----TEST THIS----
      - uses: actions/setup-python@v4   # sets up a python environment for use
      - name: Install dependencies
        run: |                                  
          python -m pip install --upgrade pip
          pip install -U sphinx
          pip install sphinx-autodoc-typehints
          pip install sphinx_rtd_theme

      - name: Run a one-line script
        run: echo Hello, world!



#jobs:
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
     # - name: Run a one-line script
     #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
